# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{negative-captcha}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["subwindow"]
  s.date = %q{2011-05-23}
  s.description = %q{Makes the process of creating a negative captcha in Rails much less painless.}
  s.email = %q{erik@skribit.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "Rakefile",
    "init.rb",
    "lib/negative-captcha.rb",
    "lib/negative_captcha_form_builder.rb",
    "lib/negative_captcha_view_helpers.rb",
    "meta.yml",
    "negative-captcha.gemspec",
    "rails/init.rb",
    "test/negative_captcha_test.rb"
  ]
  s.homepage = %q{https://github.com/stefants/negative-captcha}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Makes the process of creating a negative captcha in Rails much less painless.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

